#!/usr/bin/env sh

# Copyright 2015 the original authors.
# Gradle start up script for POSIX generated by Gradle.

DIRNAME=$(dirname "$0")
if [ -z "$DIRNAME" ]; then
  DIRNAME=.
fi
APP_BASE_NAME=$(basename "$0")
APP_HOME=$(cd "$DIRNAME"; pwd)

DEFAULT_JVM_OPTS=""

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

JAVA_CMD=java

if [ -n "$JAVA_HOME" ] ; then
    JAVA_CMD="$JAVA_HOME/bin/java"
fi

exec "$JAVA_CMD" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
